tools:
  - name: eslint
    languages: [Javascript, TypeScript]
    extensions: [.js, .jsm, .jsx, .mjs, .cjs, .ts, .tsx]
    files: []
  - name: lizard
    languages: [Javascript, TypeScript]
    extensions: [.js, .jsm, .jsx, .mjs, .cjs, .ts, .tsx]
    files: []
  - name: opengrep
    languages: [Dockerfile, Javascript, JSON, Shell, TypeScript, YAML]
    extensions:
      [.bash, .dockerfile, .js, .jsm, .json, .jsx, .mjs, .cjs, .sh, .ts, .tsx, .yaml, .yml]
    files: [Dockerfile]
  - name: trivy
    languages: [Dockerfile, JSON, Javascript, TypeScript, XML, YAML]
    extensions:
      [.dockerfile, .js, .jsm, .json, .jsx, .mjs, .cjs, .ts, .tsx, .wsdl, .xml, .xsl, .yaml, .yml]
    files: [Dockerfile, package-lock.json, package.json, pnpm-lock.yaml, yarn.lock]
