#!/usr/bin/env python3
"""PreToolUse hook — blocks edits to generated/cached paths that should never be hand-edited.

Blocked paths:
  - dist/           Generated by `npm run build`. Silently reverted by git pull.
  - DocVault/specflow/*/templates/  Runtime template cache. Overwritten on every MCP boot.
  - DocVault/Projects/SpecFlow/Templates/  KB snapshots. Overwritten by /publish-templates.
"""

import json
import sys

BLOCKED = [
    ("/dist/", "dist/ is generated by `npm run build`. Edit src/ and rebuild."),
    (
        "DocVault/specflow/templates/",
        "DocVault/specflow/templates/ is a global runtime cache overwritten on every MCP boot. "
        "Edit src/markdown/templates/ instead, or create a user override in "
        "DocVault/specflow/user-templates/ (see CLAUDE.md § Template Source of Truth).",
    ),
    (
        "DocVault/Projects/SpecFlow/Templates/",
        "DocVault/Projects/SpecFlow/Templates/ is a KB snapshot regenerated by /publish-templates. "
        "Edit src/markdown/templates/ instead.",
    ),
]


def main():
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        return

    tool_name = data.get("tool_name", "")
    if tool_name not in ("Edit", "Write"):
        return

    file_path = data.get("tool_input", {}).get("file_path", "")
    if not file_path:
        return

    for pattern, reason in BLOCKED:
        if pattern in file_path:
            print(json.dumps({"decision": "block", "reason": reason}))
            return


if __name__ == "__main__":
    main()
